### Credit card dataset
- Time: time elapsed since the first transaction.
- Amount: transaction amount.
- Class: fraud label, where 1 is fraud and 0 is legitimate.
- V1 to V28: anonymized PCA features.

### AML transaction dataset
- This dataset contains transaction-level AML information.
- It also includes pattern files for laundering behavior.
- The exact column names should be inspected directly in the loaded files because they can vary by subset.

**IMPORTING LIBRARIES**

In [1]:
import pandas as pd
import os

**IMPORTING AND INSPECTING DATA**

In [4]:
os.listdir()

['.bashrc',
 '.bash_history',
 '.bash_profile',
 '.cache',
 '.claude',
 '.claude.json',
 '.config',
 '.copilot',
 '.docker',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.local',
 '.vscode',
 '.vscode-shared',
 '01_project_setup.ipynb',
 '3D Objects',
 'AppData',
 'Application Data',
 'battery-report.html',
 'Contacts',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'New folder',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Videos']

In [7]:
os.chdir(r"C:\Users\PC\Desktop\Transaction-and-AML-Risk-Monitoring-System")
os.getcwd()

'C:\\Users\\PC\\Desktop\\Transaction-and-AML-Risk-Monitoring-System'

In [8]:
os.listdir("data")

['creditcard.csv',
 'HI-Large_accounts.csv',
 'HI-Large_Patterns.txt',
 'HI-Large_Trans.csv',
 'HI-Medium_accounts.csv',
 'HI-Medium_Patterns.txt',
 'HI-Medium_Trans.csv',
 'HI-Small_accounts.csv',
 'HI-Small_Patterns.txt',
 'HI-Small_Trans.csv',
 'LI-Large_accounts.csv',
 'LI-Large_Patterns.txt',
 'LI-Large_Trans.csv',
 'LI-Medium_accounts.csv',
 'LI-Medium_Patterns.txt',
 'LI-Medium_Trans.csv',
 'LI-Small_accounts.csv',
 'LI-Small_Patterns.txt',
 'LI-Small_Trans.csv']

In [10]:
cc = pd.read_csv(r"data\creditcard.csv")
aml_trans = pd.read_csv(r"data\HI-Small_Trans.csv")
aml_accounts = pd.read_csv(r"data\HI-Small_accounts.csv")

In [11]:
cc.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [13]:
cc.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='str')

In [14]:
cc.shape

(284807, 31)

In [16]:
cc["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [17]:
aml_trans.head()

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving Currency,Amount Paid,Payment Currency,Payment Format,Is Laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0

In [18]:
aml_trans.columns

Index(['Timestamp', 'From Bank', 'Account', 'To Bank', 'Account.1',
       'Amount Received', 'Receiving Currency', 'Amount Paid',
       'Payment Currency', 'Payment Format', 'Is Laundering'],
      dtype='str')

In [19]:
aml_accounts.head()

,Bank Name,Bank ID,Account Number,Entity ID,Entity Name
0,Portugal Bank #4507,331579,80B779D80,80062E240,Sole Proprietorship #50438
1,Canada Bank #27,210,809D86900,800C998A0,Corporation #33520
2,UK Bank #33,21884,80812BE00,800C47F50,Partnership #35397
3,Germany Bank #4815,32742,81047F300,80096F0B0,Corporation #48813
4,National Bank of Harrisburg,127390,80BD8CF00,800FB8760,Corporation #889

In [21]:
aml_accounts.columns

Index(['Bank Name', 'Bank ID', 'Account Number', 'Entity ID', 'Entity Name'], dtype='str')

In [22]:
aml_accounts.isna().sum()

Bank Name         0
Bank ID           0
Account Number    0
Entity ID         0
Entity Name       0
dtype: int64

**DATA CLAEANING**

In [24]:
cc = cc.copy()
cc.columns = cc.columns.str.strip().str.lower()
cc.duplicated().sum()

np.int64(1081)

In [25]:
cc = cc.drop_duplicates()

In [27]:
aml_trans = aml_trans.copy()
aml_trans.columns = aml_trans.columns.str.strip().str.lower()
aml_trans.duplicated().sum()

np.int64(9)

In [28]:
aml_trans = aml_trans.drop_duplicates()

In [29]:
aml_accounts = aml_accounts.copy()
aml_accounts.columns = aml_accounts.columns.str.strip().str.lower()
aml_accounts.duplicated().sum()

np.int64(0)

In [31]:
cc.columns

Index(['time', 'v1', 'v2', 'v3', 'v4', 'v5', 'v6', 'v7', 'v8', 'v9', 'v10',
       'v11', 'v12', 'v13', 'v14', 'v15', 'v16', 'v17', 'v18', 'v19', 'v20',
       'v21', 'v22', 'v23', 'v24', 'v25', 'v26', 'v27', 'v28', 'amount',
       'class'],
      dtype='str')

**Save cleaned copies**

In [32]:
cc.to_csv(r"data\cleaned_creditcard.csv", index=False)
aml_trans.to_csv(r"data\cleaned_HI-Small_Trans.csv", index=False)
aml_accounts.to_csv(r"data\cleaned_HI-Small_accounts.csv", index=False)

In [33]:
cc

,time,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v21,v22,v23,v24,v25,v26,v27,v28,amount,class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

**CREATING FRAUD FEATURES**

In [34]:
import numpy as np

cc["hour"] = (cc["time"] // 3600) % 24
cc["amount_log"] = np.log1p(cc["amount"])
cc.head()

,time,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v23,v24,v25,v26,v27,v28,amount,class,hour,amount_log
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0,0.0,5.014760
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0,0.0,1.305626
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0,0.0,5.939276
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0,0.0,4.824306
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0,0.0,4.262539

In [36]:
aml_trans

,timestamp,from bank,account,to bank,account.1,amount received,receiving currency,amount paid,payment currency,payment format,is laundering
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,US Dollar,3697.340000,US Dollar,Reinvestment,0
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,US Dollar,0.010000,US Dollar,Cheque,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,US Dollar,14675.570000,US Dollar,Reinvestment,0
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,US Dollar,2806.970000,US Dollar,Reinvestment,0
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,US Dollar,36682.970000,US Dollar,Reinvestment,0
...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,Bitcoin,0.154978,Bitcoin,Bitcoin,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,Bitcoin,0.108128,Bitcoin,Bitcoin,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,Bitcoin,0.004988,Bitcoin,Bitcoin,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,Bitcoin,0.038417,Bitcoin,Bitcoin,0
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,Bitcoin,0.281983,Bitcoin,Bitcoin,0

In [37]:
aml_trans = aml_trans.copy()

aml_trans.columns = [
    "timestamp", "from_bank", "account", "to_bank", "account_1",
    "amount_received", "receiving_currency", "amount_paid",
    "payment_currency", "payment_format", "is_laundering"
]

aml_trans["timestamp"] = pd.to_datetime(aml_trans["timestamp"], errors="coerce")
aml_trans["hour"] = aml_trans["timestamp"].dt.hour
aml_trans["same_currency"] = (aml_trans["receiving_currency"] == aml_trans["payment_currency"]).astype(int)
aml_trans["cross_bank"] = (aml_trans["from_bank"] != aml_trans["to_bank"]).astype(int)
aml_trans["amount_ratio"] = aml_trans["amount_paid"] / aml_trans["amount_received"].replace(0, pd.NA)

aml_trans.head()

,timestamp,from_bank,account,to_bank,account_1,amount_received,receiving_currency,amount_paid,payment_currency,payment_format,is_laundering,hour,same_currency,cross_bank,amount_ratio
0,2022-09-01 00:20:00,10,8000EBD30,10,8000EBD30,3697.34,US Dollar,3697.34,US Dollar,Reinvestment,0,0,1,0,1.0
1,2022-09-01 00:20:00,3208,8000F4580,1,8000F5340,0.01,US Dollar,0.01,US Dollar,Cheque,0,0,1,1,1.0
2,2022-09-01 00:00:00,3209,8000F4670,3209,8000F4670,14675.57,US Dollar,14675.57,US Dollar,Reinvestment,0,0,1,0,1.0
3,2022-09-01 00:02:00,12,8000F5030,12,8000F5030,2806.97,US Dollar,2806.97,US Dollar,Reinvestment,0,0,1,0,1.0
4,2022-09-01 00:06:00,10,8000F5200,10,8000F5200,36682.97,US Dollar,36682.97,US Dollar,Reinvestment,0,0,1,0,1.0

**AML summary features**




-This gives a basic risk view per account

In [40]:
aml_summary = aml_trans.groupby("account").agg(
    total_paid=("amount_paid", "sum"),
    total_received=("amount_received", "sum"),
    txn_count=("timestamp", "count"),
    avg_paid=("amount_paid", "mean"),
    laundering_count=("is_laundering", "sum")
).reset_index()

aml_summary["laundering_rate"] = aml_summary["laundering_count"] / aml_summary["txn_count"]
aml_summary.head()

,account,total_paid,total_received,txn_count,avg_paid,laundering_count,laundering_rate
0,100428660,5.276229e+10,5.276229e+10,168672,3.128100e+05,243,0.001441
1,1004286A8,2.606938e+10,2.606938e+10,103018,2.530565e+05,158,0.001534
2,1004286F0,2.465736e+10,2.465736e+10,18663,1.321189e+06,21,0.001125
3,100428738,2.592168e+11,2.592168e+11,13756,1.884391e+07,23,0.001672
4,100428780,3.739337e+11,3.739337e+11,17264,2.165974e+07,21,0.001216

**Find suspicious accounts**

In [41]:
aml_summary.sort_values("laundering_rate", ascending=False).head(10)

,account,total_paid,total_received,txn_count,avg_paid,laundering_count,laundering_rate
206918,808619C40,1346.57,1346.57,1,1346.57,1,1.0
256211,80A678FB0,120.69,120.69,1,120.69,1,1.0
319597,80D0C4F20,2964.49,2964.49,1,2964.49,1,1.0
119192,804CB2130,102703.73,102703.73,1,102703.73,1,1.0
79621,80330A900,4131.18,4131.18,1,4131.18,1,1.0
318212,80CFCC610,210250.84,210250.84,1,210250.84,1,1.0
340442,80DEB5300,465.24,465.24,1,465.24,1,1.0
38484,80189D920,302.52,302.52,1,302.52,1,1.0
423925,811645E20,13731.57,13731.57,1,13731.57,1,1.0
464485,8132265D0,572.78,572.78,1,572.78,1,1.0

**Build transaction fraud insights**

In [42]:
cc["hour"] = (cc["time"] // 3600) % 24
cc["amount_log"] = np.log1p(cc["amount"])

In [43]:
cc.groupby("class")[["amount", "amount_log", "hour"]].mean()

           amount  amount_log       hour
class
0       88.413575    3.154289  14.049638
1      123.871860    2.837549  11.655391

### Initial Insights
- Credit card fraud is highly imbalanced.
- AML accounts with higher laundering rates may deserve closer review.
- Time and amount features may help identify suspicious activity.

### Analysis
- The credit card dataset is highly imbalanced, so fraud is rare and needs careful interpretation.

- The AML dataset now has account-level summaries that help highlight suspicious behaviour.

- The laundering_rate ranking is a useful first-pass risk filter.

- amount, time, and transaction patterns are the main starting features for investigation.

**Rank suspicious accounts**

In [45]:
aml_summary.sort_values("laundering_rate", ascending=False).head(10)

,account,total_paid,total_received,txn_count,avg_paid,laundering_count,laundering_rate
206918,808619C40,1346.57,1346.57,1,1346.57,1,1.0
256211,80A678FB0,120.69,120.69,1,120.69,1,1.0
319597,80D0C4F20,2964.49,2964.49,1,2964.49,1,1.0
119192,804CB2130,102703.73,102703.73,1,102703.73,1,1.0
79621,80330A900,4131.18,4131.18,1,4131.18,1,1.0
318212,80CFCC610,210250.84,210250.84,1,210250.84,1,1.0
340442,80DEB5300,465.24,465.24,1,465.24,1,1.0
38484,80189D920,302.52,302.52,1,302.52,1,1.0
423925,811645E20,13731.57,13731.57,1,13731.57,1,1.0
464485,8132265D0,572.78,572.78,1,572.78,1,1.0

**Risk Flag**

In [46]:
aml_summary["risk_level"] = pd.cut(
    aml_summary["laundering_rate"],
    bins=[-0.01, 0.05, 0.20, 1.00],
    labels=["Low", "Medium", "High"]
)

aml_summary.head()

,account,total_paid,total_received,txn_count,avg_paid,laundering_count,laundering_rate,risk_level
0,100428660,5.276229e+10,5.276229e+10,168672,3.128100e+05,243,0.001441,Low
1,1004286A8,2.606938e+10,2.606938e+10,103018,2.530565e+05,158,0.001534,Low
2,1004286F0,2.465736e+10,2.465736e+10,18663,1.321189e+06,21,0.001125,Low
3,100428738,2.592168e+11,2.592168e+11,13756,1.884391e+07,23,0.001672,Low
4,100428780,3.739337e+11,3.739337e+11,17264,2.165974e+07,21,0.001216,Low

In [47]:
aml_summary.to_csv(r"data\processed\aml_summary.csv", index=False)

### Key Findings
- Credit card fraud is highly imbalanced.
- AML monitoring benefits from account-level summaries.
- High laundering-rate accounts deserve priority review.
- Transaction amount and time are useful early indicators.